### ISSUE TITLE
Apache2 config

### ISSUE THREAD

**Issue by cwild** [aelintra/sail#2]
I upgraded to 5.0 from 4.1 and noticed the web interface changes to redirect to SSL. Not sure if it's just the configuration on my box or not (I may have modified the config in the past) but I had to run `a2enmod ssl`.

Maybe worthy of inclusion in the postinst?

https://github.com/aelintra/sail/blob/9e203b59f4892b9b9fe28678bd2d3312b62b7418/sail-5.0.0/debian/postinst#L116-L118

Apologies if I am just being dumb!

**Comment by aelintra** [comment]
You aren't being dumb.  You are just trying to run a work-in-progress.
I'm in the middle of packaging so it's not finished yet, I just committed
my work and built a deb for initial test on a target VM.   It's got loads
of greenies in it at the moment, one of which is the key creation in the
postinst; there isn't any yet!   If you want it to work as-is, you'll need
to do this

sudo a2enmod ssl
*mkdir /etc/apache2/key*
*mkdir /etc/apache2/crt*
*cd /etc/apache2*
*openssl req -new -x509 -days 365 -keyout key/vhost1.key -out
crt/vhost1.crt -nodes -subj "/O=Aelintra/OU=PBX/CN=sark.local"*

Finally, you'll need to modify the sark-ssl (in sites-available) to make
the cert and key entries point to the ones you've just created.   After
that you'll be golden but there are still issues in the code to be resolved
so let me know what you find.


:-)

**Comment by cwild** [comment]
Apologies for the delay! All working now following your instructions. Many thanks.
